# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.1

    working_directory: ~/beestock-admin-dashboard

    steps:
      - checkout

      - run:
          name: Install Project Dependencies
          command: npm install
          working_directory: ~/beestock-admin-dashboard/vuejs-app

      - run:
          name: Build The Project - Production Version
          command: npm run build
          working_directory: ~/beestock-admin-dashboard/vuejs-app

      - run:
         name: Clear ~/.ssh/known_hosts and Add host admin.beesstock.com to it
         command: ssh-keyscan admin.beesstock.com > ~/.ssh/known_hosts

      - deploy:
          name: Deploy dist/ to remote 'admin.beestock.com' instance
          command: scp -rp dist/ ubuntu@admin.beesstock.com:~/project/
          working_directory: ~/beestock-admin-dashboard/vuejs-app

      - run:
          name: Restart The Application - Using 'forever'
          command: ssh ubuntu@admin.beesstock.com 'forever restart -a -l ~/project/logs/forever.log -o ~/project/logs/out.log -e ~/project/logs/error.log ~/project/server.js'